/**
 * Crew Load Sheet Generator
 * Generates truck load list - no prices, just quantities
 */

import jsPDF from 'jspdf';
import { buildTakeoff } from '../materials/canonicalTakeoffEngine';

export async function generateCrewLoadSheet(job, runs, gates, materials, fenceLines = []) {
  const pdf = new jsPDF();
  let yPos = 15;
  
  // Get canonical takeoff for consistent post counts
  const takeoff = buildTakeoff(job, fenceLines, runs, gates);
  const { postCounts } = takeoff;
  
  // Aggregate materials by line item name
  const aggregatedMaterials = materials.reduce((acc, item) => {
    const qty = item.manualOverrideQty || item.quantityCalculated || item.calculatedQty || item.quantity || 0;
    const key = item.materialDescription || item.lineItemName;
    
    if (!acc[key]) {
      acc[key] = {
        lineItemName: item.materialDescription || item.lineItemName,
        totalQty: 0,
        unit: item.uom || item.unit,
        calculationDetails: item.notes || item.calculationDetails || ''
      };
    }
    
    acc[key].totalQty += qty;
    return acc;
  }, {});
  
  const aggregatedMaterialsList = Object.values(aggregatedMaterials);
  
  // Header
  pdf.setFillColor(16, 113, 84);
  pdf.rect(0, 0, 210, 40, 'F');
  
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(24);
  pdf.setFont(undefined, 'bold');
  pdf.text('CREW LOAD SHEET', 105, 20, { align: 'center' });
  
  pdf.setFontSize(16);
  pdf.text(job.jobNumber, 105, 30, { align: 'center' });
  
  pdf.setTextColor(0, 0, 0);
  yPos = 50;
  
  // Job Info
  pdf.setFontSize(10);
  pdf.setFont(undefined, 'bold');
  pdf.text('Customer:', 20, yPos);
  pdf.setFont(undefined, 'normal');
  pdf.text(job.customerName, 60, yPos);
  yPos += 6;
  
  pdf.setFont(undefined, 'bold');
  pdf.text('Address:', 20, yPos);
  pdf.setFont(undefined, 'normal');
  pdf.text(`${job.addressLine1}, ${job.city}, ${job.state}`, 60, yPos);
  yPos += 6;
  
  pdf.setFont(undefined, 'bold');
  pdf.text('Total LF:', 20, yPos);
  pdf.setFont(undefined, 'normal');
  pdf.text(String(job.totalLF), 60, yPos);
  yPos += 10;
  
  // A) POSTS
  yPos = addSection(pdf, yPos, 'POSTS', aggregatedMaterialsList.filter(m => 
    /postmaster/i.test(m.lineItemName) || 
    (/post/i.test(m.lineItemName) && !/cap/i.test(m.lineItemName))
  ));
  
  // B) PANELS / PICKETS / SECTIONS
  yPos = addSection(pdf, yPos, 'PANELS / PICKETS / SECTIONS', aggregatedMaterialsList.filter(m => 
    /picket/i.test(m.lineItemName) || 
    /panel/i.test(m.lineItemName) ||
    /board.*board/i.test(m.lineItemName) ||
    /furring/i.test(m.lineItemName) ||
    /cap.*strip/i.test(m.lineItemName)
  ));
  
  // C) GATES
  yPos = addGatesSection(pdf, yPos, gates, runs, aggregatedMaterialsList);
  
  // D) FASTENERS
  yPos = addSection(pdf, yPos, 'FASTENERS', aggregatedMaterialsList.filter(m => 
    /screw/i.test(m.lineItemName) || 
    /nail/i.test(m.lineItemName) ||
    /fastener/i.test(m.lineItemName)
  ));
  
  // E) CONCRETE / FOOTINGS
  yPos = addSection(pdf, yPos, 'CONCRETE / FOOTINGS', aggregatedMaterialsList.filter(m => 
    /concrete/i.test(m.lineItemName) || 
    /bag/i.test(m.lineItemName)
  ));
  
  // Footer
  if (yPos > 250) {
    pdf.addPage();
    yPos = 20;
  }
  
  yPos += 10;
  pdf.setDrawColor(200, 200, 200);
  pdf.line(20, yPos, 190, yPos);
  yPos += 5;
  
  pdf.setFontSize(8);
  pdf.setTextColor(120, 120, 120);
  pdf.text('✓ All quantities validated and include waste allowance', 105, yPos, { align: 'center' });
  yPos += 4;
  pdf.text('Generated by FenceBuddy | No prices shown - load sheet only', 105, yPos, { align: 'center' });
  yPos += 4;
  pdf.setFontSize(7);
  pdf.text(`Takeoff Audit: End: ${postCounts.endPosts} | Corner: ${postCounts.cornerPosts} | Gate: ${postCounts.gatePosts} | Line: ${postCounts.linePosts} | Total: ${postCounts.totalVinylPosts}`, 105, yPos, { align: 'center' });
  
  return pdf;
}

function addSection(pdf, yPos, title, items) {
  if (items.length === 0) return yPos;
  
  if (yPos > 250) {
    pdf.addPage();
    yPos = 20;
  }
  
  // Section header
  pdf.setFillColor(16, 113, 84);
  pdf.rect(20, yPos - 5, 170, 8, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(11);
  pdf.setFont(undefined, 'bold');
  pdf.text(title, 23, yPos);
  pdf.setTextColor(0, 0, 0);
  yPos += 8;
  
  // Items
  pdf.setFontSize(9);
  pdf.setFont(undefined, 'normal');
  
  items.forEach((item, idx) => {
    if (yPos > 270) {
      pdf.addPage();
      yPos = 20;
    }
    
    if (idx % 2 === 0) {
      pdf.setFillColor(250, 250, 250);
      pdf.rect(20, yPos - 4, 170, 7, 'F');
    }
    
    const qty = item.totalQty || item.manualOverrideQty || item.calculatedQty || item.quantity || 0;
    pdf.setFont(undefined, 'bold');
    pdf.text(String(qty), 23, yPos);
    pdf.setFont(undefined, 'normal');
    pdf.text(item.unit, 40, yPos);
    pdf.text(item.lineItemName, 60, yPos, { maxWidth: 125 });
    yPos += 7;
  });
  
  yPos += 5;
  return yPos;
}

function addGatesSection(pdf, yPos, gates, runs, materials) {
  if (gates.length === 0) return yPos;
  
  if (yPos > 250) {
    pdf.addPage();
    yPos = 20;
  }
  
  // Section header
  pdf.setFillColor(16, 113, 84);
  pdf.rect(20, yPos - 5, 170, 8, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(11);
  pdf.setFont(undefined, 'bold');
  pdf.text('GATES', 23, yPos);
  pdf.setTextColor(0, 0, 0);
  yPos += 8;
  
  pdf.setFontSize(9);
  
  gates.forEach((gate, idx) => {
    if (yPos > 265) {
      pdf.addPage();
      yPos = 20;
    }
    
    const run = runs.find(r => r.id === gate.runId);
    const location = run ? run.runLabel : 'Unknown';
    
    // Gate info
    if (idx % 2 === 0) {
      pdf.setFillColor(250, 250, 250);
      pdf.rect(20, yPos - 4, 170, 18, 'F');
    }
    
    pdf.setFont(undefined, 'bold');
    pdf.text(`${gate.gateType} Gate - ${gate.gateWidth}`, 23, yPos);
    pdf.setFont(undefined, 'normal');
    pdf.setTextColor(100, 100, 100);
    pdf.setFontSize(8);
    pdf.text(`Location: ${location}`, 23, yPos + 4);
    pdf.setFontSize(9);
    pdf.setTextColor(0, 0, 0);
    
    // Hardware summary
    const leafCount = gate.gateType === 'Double' ? 2 : 1;
    yPos += 8;
    pdf.text(`• ${leafCount} handle${leafCount > 1 ? 's' : ''} (1 per leaf)`, 25, yPos);
    yPos += 4;
    
    if (gate.gateType === 'Double') {
      pdf.text(`• 2 cane bolts/drop rods (1 per leaf)`, 25, yPos);
      yPos += 4;
    }
    
    pdf.text(`• Hinges per standard`, 25, yPos);
    yPos += 8;
  });
  
  yPos += 5;
  return yPos;
}