/**
 * Supplier Export Generator
 * Prepares materials for supplier ordering (CSV/PDF)
 */

import jsPDF from 'jspdf';

/**
 * Generate supplier CSV export
 */
export function generateSupplierCSV(materials) {
  const rows = [
    ['Category', 'Item Name', 'Quantity', 'Unit', 'Notes']
  ];
  
  // Aggregate materials first
  const aggregatedMaterials = aggregateMaterials(materials);
  const categorized = categorizeMaterials(aggregatedMaterials);
  
  Object.entries(categorized).forEach(([category, items]) => {
    items.forEach(item => {
      const qty = item.totalQty || item.manualOverrideQty || item.calculatedQty || item.quantity || 0;
      rows.push([
        category,
        item.lineItemName,
        qty,
        item.unit,
        item.calculationDetails || ''
      ]);
    });
  });
  
  return rows.map(row => row.map(cell => `"${cell}"`).join(',')).join('\n');
}

/**
 * Generate supplier PDF export
 */
export function generateSupplierPDF(job, materials) {
  const pdf = new jsPDF();
  let yPos = 15;
  
  // Aggregate materials first
  const aggregatedMaterials = aggregateMaterials(materials);
  
  // Header
  pdf.setFillColor(16, 113, 84);
  pdf.rect(0, 0, 210, 35, 'F');
  
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(20);
  pdf.setFont(undefined, 'bold');
  pdf.text('SUPPLIER ORDER', 105, 18, { align: 'center' });
  
  pdf.setFontSize(12);
  pdf.text(`Job: ${job.jobNumber} | ${job.customerName}`, 105, 28, { align: 'center' });
  
  pdf.setTextColor(0, 0, 0);
  yPos = 45;
  
  // Categorized materials
  const categorized = categorizeMaterials(aggregatedMaterials);
  
  Object.entries(categorized).forEach(([category, items]) => {
    if (yPos > 250) {
      pdf.addPage();
      yPos = 20;
    }
    
    // Category header
    pdf.setFillColor(220, 220, 220);
    pdf.rect(15, yPos - 5, 180, 8, 'F');
    pdf.setFontSize(11);
    pdf.setFont(undefined, 'bold');
    pdf.text(category.toUpperCase(), 20, yPos);
    yPos += 10;
    
    // Items
    pdf.setFontSize(9);
    pdf.setFont(undefined, 'normal');
    
    items.forEach((item, idx) => {
      if (yPos > 270) {
        pdf.addPage();
        yPos = 20;
      }
      
      if (idx % 2 === 1) {
        pdf.setFillColor(250, 250, 250);
        pdf.rect(15, yPos - 4, 180, 7, 'F');
      }
      
      const qty = item.totalQty || item.manualOverrideQty || item.calculatedQty || item.quantity || 0;
      pdf.setFont(undefined, 'bold');
      pdf.text(String(qty), 18, yPos);
      pdf.setFont(undefined, 'normal');
      pdf.text(item.unit, 35, yPos);
      pdf.text(item.lineItemName, 55, yPos, { maxWidth: 135 });
      yPos += 7;
    });
    
    yPos += 5;
  });
  
  // Footer
  yPos += 5;
  pdf.setFontSize(8);
  pdf.setTextColor(120, 120, 120);
  pdf.text('Generated by FenceBuddy | For supplier ordering only', 105, yPos, { align: 'center' });

  return pdf;
  }

/**
 * Aggregate materials by line item name
 */
function aggregateMaterials(materials) {
  const aggregated = materials.reduce((acc, item) => {
    const qty = item.manualOverrideQty || item.quantityCalculated || item.calculatedQty || item.quantity || 0;
    const key = item.materialDescription || item.lineItemName;
    
    if (!acc[key]) {
      acc[key] = {
        lineItemName: item.materialDescription || item.lineItemName,
        totalQty: 0,
        unit: item.uom || item.unit,
        calculationDetails: item.notes || item.calculationDetails || ''
      };
    }
    
    acc[key].totalQty += qty;
    return acc;
  }, {});
  
  return Object.values(aggregated);
}

/**
 * Categorize materials for supplier grouping
 */
function categorizeMaterials(materials) {
  const categories = {
    'Posts': [],
    'Panels / Pickets': [],
    'Gates': [],
    'Hardware': [],
    'Fasteners': [],
    'Concrete': [],
    'Other': []
  };
  
  materials.forEach(item => {
    if (/post/i.test(item.lineItemName) && !/cap/i.test(item.lineItemName)) {
      categories['Posts'].push(item);
    } else if (/picket/i.test(item.lineItemName) || /panel/i.test(item.lineItemName)) {
      categories['Panels / Pickets'].push(item);
    } else if (/gate/i.test(item.lineItemName)) {
      categories['Gates'].push(item);
    } else if (/handle|hinge|latch|bolt/i.test(item.lineItemName)) {
      categories['Hardware'].push(item);
    } else if (/screw|nail|fastener/i.test(item.lineItemName)) {
      categories['Fasteners'].push(item);
    } else if (/concrete|bag/i.test(item.lineItemName)) {
      categories['Concrete'].push(item);
    } else {
      categories['Other'].push(item);
    }
  });
  
  // Remove empty categories
  Object.keys(categories).forEach(key => {
    if (categories[key].length === 0) {
      delete categories[key];
    }
  });
  
  return categories;
}