{
  "priceBookVersion": "1.0",
  "supplier": "Stephens Pipe & Steel",
  "fenceMaterial": "Vinyl",
  "fenceHeight": "6ft",
  "fenceColor": "White",
  "lastUpdated": "2025-12-28",
  "notes": "Supplier net costs - no markup, no labor, no tax. Gate posts override corner/end posts at same coordinate.",
  "canonicalRules": {
    "galvanizedPostsLTE": "totalVinylPosts",
    "donuts": "galvanizedPosts * 2",
    "gatePostsPerGate": 2,
    "gatePostDominance": true,
    "concreteOnlyForGatePosts": true,
    "panelsRoundedUp": true,
    "materialTypeFiltered": true
  },
  "materials": [
    {
      "materialCategory": "Panel",
      "materialName": "6' White Vinyl Privacy Panel",
      "spec": "8' Wide Solid Privacy Section",
      "unit": "each",
      "unitCost": 98.65,
      "supplier": "Stephens Pipe & Steel",
      "height": "6ft",
      "color": "White",
      "calculationRule": "1 panel per 8 LF",
      "isStructural": false,
      "affectsPricing": true,
      "allowOverride": false,
      "notes": "8' panel width - round up to nearest whole panel"
    },
    {
      "materialCategory": "Vinyl Post",
      "materialName": "5x5 Vinyl Line Post",
      "spec": "5x5x105",
      "unit": "each",
      "unitCost": 25.71,
      "supplier": "Stephens Pipe & Steel",
      "height": "6ft",
      "color": "White",
      "calculationRule": "Per line post from map",
      "isStructural": false,
      "affectsPricing": true,
      "allowOverride": false,
      "notes": "Cosmetic shell - requires galvanized reinforcement"
    },
    {
      "materialCategory": "Vinyl Post",
      "materialName": "5x5 Vinyl End Post",
      "spec": "5x5x105",
      "unit": "each",
      "unitCost": 25.71,
      "supplier": "Stephens Pipe & Steel",
      "height": "6ft",
      "color": "White",
      "calculationRule": "Per end post from graph",
      "isStructural": false,
      "affectsPricing": true,
      "allowOverride": false,
      "notes": "Cosmetic shell - requires galvanized reinforcement"
    },
    {
      "materialCategory": "Vinyl Post",
      "materialName": "5x5 Vinyl Corner Post",
      "spec": "5x5x105",
      "unit": "each",
      "unitCost": 25.71,
      "supplier": "Stephens Pipe & Steel",
      "height": "6ft",
      "color": "White",
      "calculationRule": "Per corner post from graph",
      "isStructural": false,
      "affectsPricing": true,
      "allowOverride": false,
      "notes": "Cosmetic shell - requires galvanized reinforcement"
    },
    {
      "materialCategory": "Vinyl Post",
      "materialName": "5x5 Vinyl Gate Post",
      "spec": "5x5x105",
      "unit": "each",
      "unitCost": 25.71,
      "supplier": "Stephens Pipe & Steel",
      "height": "6ft",
      "color": "White",
      "calculationRule": "2 per gate - overrides corner/end posts at same coordinate",
      "isStructural": false,
      "affectsPricing": true,
      "allowOverride": false,
      "notes": "Gate post dominance applies - cosmetic shell"
    },
    {
      "materialCategory": "Post Reinforcement",
      "materialName": "2.5\" Galvanized Post",
      "spec": "2-1/2\" x 8' x .130 (40) No-Perforation",
      "unit": "each",
      "unitCost": 19.80,
      "supplier": "Stephens Pipe & Steel",
      "height": "6ft",
      "color": "N/A",
      "calculationRule": "1 per vinyl post (all types)",
      "isStructural": true,
      "affectsPricing": true,
      "allowOverride": false,
      "notes": "Structural reinforcement for ALL vinyl posts - must not exceed total vinyl posts"
    },
    {
      "materialCategory": "Post Reinforcement",
      "materialName": "No-Dig Donut",
      "spec": "Post Stabilizer",
      "unit": "each",
      "unitCost": 4.50,
      "supplier": "Stephens Pipe & Steel",
      "height": "6ft",
      "color": "N/A",
      "calculationRule": "2 per galvanized post",
      "isStructural": true,
      "affectsPricing": true,
      "allowOverride": false,
      "notes": "Post stabilization - 2 required per driven post"
    },
    {
      "materialCategory": "Post Cap",
      "materialName": "Vinyl Post Cap",
      "spec": "5x5 Post Cap",
      "unit": "each",
      "unitCost": 3.24,
      "supplier": "Stephens Pipe & Steel",
      "height": "6ft",
      "color": "White",
      "calculationRule": "1 per vinyl post (exclude gate posts if capped separately)",
      "isStructural": false,
      "affectsPricing": true,
      "allowOverride": false,
      "notes": "Decorative cap for all vinyl posts"
    },
    {
      "materialCategory": "Gate Structure",
      "materialName": "Aluminum Gate Beam",
      "spec": "5x5x96 I-Beam Reinforcement",
      "unit": "each",
      "unitCost": 70.43,
      "supplier": "Stephens Pipe & Steel",
      "height": "6ft",
      "color": "N/A",
      "calculationRule": "1 per gate post (2 per gate)",
      "isStructural": true,
      "affectsPricing": true,
      "allowOverride": false,
      "notes": "Heavy-duty I-beam reinforcement for gate posts"
    },
    {
      "materialCategory": "Gate Structure",
      "materialName": "Quick Crete",
      "spec": "50 lb Bag Fast-Set Concrete",
      "unit": "each",
      "unitCost": 3.89,
      "supplier": "Stephens Pipe & Steel",
      "height": "6ft",
      "color": "N/A",
      "calculationRule": "2 bags per gate post",
      "isStructural": true,
      "affectsPricing": true,
      "allowOverride": false,
      "notes": "Concrete ONLY for gate posts - line/corner/end posts are driven"
    },
    {
      "materialCategory": "Gate",
      "materialName": "4' Vinyl Single Gate",
      "spec": "4ft x 6ft Single Gate",
      "unit": "each",
      "unitCost": 279.53,
      "supplier": "Stephens Pipe & Steel",
      "height": "6ft",
      "color": "White",
      "calculationRule": "Per 4' single gate",
      "isStructural": false,
      "affectsPricing": true,
      "allowOverride": false,
      "notes": "Complete gate panel - single opening"
    },
    {
      "materialCategory": "Gate",
      "materialName": "5' Vinyl Single Gate",
      "spec": "5ft x 6ft Single Gate",
      "unit": "each",
      "unitCost": 299.00,
      "supplier": "Stephens Pipe & Steel",
      "height": "6ft",
      "color": "White",
      "calculationRule": "Per 5' single gate",
      "isStructural": false,
      "affectsPricing": true,
      "allowOverride": false,
      "notes": "Complete gate panel - single opening"
    },
    {
      "materialCategory": "Gate",
      "materialName": "6' Vinyl Single Gate",
      "spec": "6ft x 6ft Single Gate",
      "unit": "each",
      "unitCost": 329.00,
      "supplier": "Stephens Pipe & Steel",
      "height": "6ft",
      "color": "White",
      "calculationRule": "Per 6' single gate",
      "isStructural": false,
      "affectsPricing": true,
      "allowOverride": false,
      "notes": "Complete gate panel - single opening"
    },
    {
      "materialCategory": "Gate",
      "materialName": "8' Vinyl Double Gate",
      "spec": "8ft x 6ft Double Gate",
      "unit": "each",
      "unitCost": 649.00,
      "supplier": "Stephens Pipe & Steel",
      "height": "6ft",
      "color": "White",
      "calculationRule": "Per 8' double gate (2 panels)",
      "isStructural": false,
      "affectsPricing": true,
      "allowOverride": false,
      "notes": "2 panels per double gate"
    },
    {
      "materialCategory": "Gate",
      "materialName": "10' Vinyl Double Gate",
      "spec": "10ft x 6ft Double Gate",
      "unit": "each",
      "unitCost": 699.00,
      "supplier": "Stephens Pipe & Steel",
      "height": "6ft",
      "color": "White",
      "calculationRule": "Per 10' double gate (2 panels)",
      "isStructural": false,
      "affectsPricing": true,
      "allowOverride": false,
      "notes": "2 panels per double gate"
    },
    {
      "materialCategory": "Gate",
      "materialName": "12' Vinyl Double Gate",
      "spec": "12ft x 6ft Double Gate",
      "unit": "each",
      "unitCost": 749.00,
      "supplier": "Stephens Pipe & Steel",
      "height": "6ft",
      "color": "White",
      "calculationRule": "Per 12' double gate (2 panels)",
      "isStructural": false,
      "affectsPricing": true,
      "allowOverride": false,
      "notes": "2 panels per double gate"
    },
    {
      "materialCategory": "Gate Hardware",
      "materialName": "Vinyl Gate Hinges",
      "spec": "TCHDMA1S3BT True-Close Hinges",
      "unit": "pair",
      "unitCost": 68.82,
      "supplier": "Stephens Pipe & Steel",
      "height": "N/A",
      "color": "Black",
      "calculationRule": "1 pair per single gate, 2 pairs per double gate",
      "isStructural": false,
      "affectsPricing": true,
      "allowOverride": false,
      "notes": "Self-closing hinge set"
    },
    {
      "materialCategory": "Gate Hardware",
      "materialName": "5\" Locklatch",
      "spec": "KLTRV-500-4D-BK Traverse Latch 5\"",
      "unit": "each",
      "unitCost": 50.87,
      "supplier": "Stephens Pipe & Steel",
      "height": "N/A",
      "color": "Black",
      "calculationRule": "1 per single gate",
      "isStructural": false,
      "affectsPricing": true,
      "allowOverride": false,
      "notes": "Single gate latch"
    },
    {
      "materialCategory": "Gate Hardware",
      "materialName": "4\" Locklatch (Double Gate)",
      "spec": "KLTRV-400-4D-BK Traverse Latch 4\"",
      "unit": "each",
      "unitCost": 50.87,
      "supplier": "Stephens Pipe & Steel",
      "height": "N/A",
      "color": "Black",
      "calculationRule": "1 per double gate",
      "isStructural": false,
      "affectsPricing": true,
      "allowOverride": false,
      "notes": "Double gate latch"
    },
    {
      "materialCategory": "Gate Hardware",
      "materialName": "Cane Bolt / Drop Rod",
      "spec": "Drop Rod for Double Gates",
      "unit": "each",
      "unitCost": 15.98,
      "supplier": "Stephens Pipe & Steel",
      "height": "N/A",
      "color": "Black",
      "calculationRule": "2 per double gate",
      "isStructural": false,
      "affectsPricing": true,
      "allowOverride": false,
      "notes": "Secures inactive leaf on double gates"
    }
  ]
}